### ISSUE TITLE
how to parse an XML document with identical tags

### ISSUE THREAD

**Issue by mattwollf** [jf-tech/omniparser#197]
I have an API that returns XML using the following structure:

```
<root>
    <objects>
        <numObjects>2</numObjects>
        <object>
            <field1></field1>
            <field2></field2>
        </object>
        <object>
            <field1></field1>
            <field2></field2>
        </object>
    </objects>
</root>
```
Is there a way to parse this using xpath/not resorting to a custom function? I tried "root/objects/object/*[position()=1]" but the omni parser picks up both objects in the output and doesnt seem capable of discriminating between the two.

the snippet from my schema:
```
 "array": [
                    {
                          "xpath": "root/objects/object/*[position()=1]",
                          "object": {
                              "key": { "const": "constValue"},
                              ...
                          }
                     }
             ]
```
 produces the output:
```
 [
        {
          "key": "constValue"
        },
        {
          "key": "constValue"
        }
      ]
```

as if the XPATH picked up both objects erroneously. it also does not populate anything in my schema based on field1 or field2 xpaths nested inside the object.

**Comment by jf-tech** [comment]
@mattwollf 

#### Test Input:
```
<root>
    <objects>
        <numObjects>4</numObjects>
        <object>
            <field1>1</field1>
            <field2>2</field2>
        </object>
        <object>
            <field1>a</field1>
            <field2>b</field2>
        </object>
        <object>
            <field1>c</field1>
            <field2>d</field2>
        </object>
        <object>
            <field1>0</field1>
            <field2>0</field2>
        </object>
    </objects>
</root>
```

####  Test Schema 1:
```
{
    "parser_settings": {
        "version": "omni.2.1",
        "file_format_type": "xml"
    },
    "transform_declarations": {
        "FINAL_OUTPUT": { "xpath": "root/objects", "object": {
            "result":  { "array": [ { "xpath": "object[position()!=1 and position()!=last()]", "object": {
                "field1": { "xpath": "field1" },
                "field2": { "xpath": "field2" }
            }}]}
        }}
    }
}
```
Output:
```
[
        {
                "result": [
                        {
                                "field1": "a",
                                "field2": "b"
                        },
                        {
                                "field1": "c",
                                "field2": "d"
                        }
                ]
        }
]
```
A few notes:
- Remember omniparser is a streaming parser, it will try to look for instances you ask it to ingest with the `xpath` filter on `FINAL_OUTPUT`. And the final result is always an array of these instances.
- In this schema, each instance is an object, anchored on xpath filter `root/objects`, thus you can see the output (from `cli.sh`) is a json array with objects (only 1 object) in it.
- This object has a single field `result`. And this field itself is defined as an object, with its own relative xpath (which show-cases some interesting filtering such as excluding the first and last `<object>`)

####  Test Schema 2:
```
{
    "parser_settings": {
        "version": "omni.2.1",
        "file_format_type": "xml"
    },
    "transform_declarations": {
        "FINAL_OUTPUT": { "array": [ { "xpath": "objects/object[position()!=1 and position()!=last()]", "object": {
            "field1": { "xpath": "field1" },
            "field2": { "xpath": "field2" }
        }}]}
    }
}
```
Output:
```
[
        [
                {
                        "field1": "a",
                        "field2": "b"
                },
                {
                        "field1": "c",
                        "field2": "d"
                }
        ]
]
```
A few notes:
- Again, you can see the `cli.sh` output is a json array. Each instance in the array is an array itself, you can see why that's the case in the test schema 2.
- This time, there is no `xpath` filtering on `FINAL_OUTPUT` - because we don't allow `xpath` filtering on `array` directly (see more details in https://github.com/jf-tech/omniparser/blob/master/doc/xpath.md and https://github.com/jf-tech/omniparser/blob/master/doc/transforms.md). By default, omniparser will simply use `'.'` (or `self` in xpath terminology) to find all the instances - and it finds one: `<root>` and put IDR anchor on `<root>`.
- Once we're inside the `array` schema, we see the element of the array should be an `object`, and its `xpath` filtering should be anchored off `<root>`, thus you see the `xpath` query starting with `objects/object`.

#### Conclusion
These are very subtle differences dealing `xpath` on `object`/`array` as well as returning instances of ingestion as `object` (which is the vast vast majority of the use cases) vs as `array` (very rare, we haven't encountered any real world use case yet, but still omniparser technically supports it)

I'm closing the ticket since your question has been answered. Reopen if you have additional asks.

**Comment by jf-tech** [comment]
@mattwollf btw, (shameless plug here), if possible, please consider financially sponsoring the project so we can continue to provide technical support and future feature expansions. Cheers!

**Comment by mattwollf** [comment]
i'll certainly look I am writing without finishing testing everything to say: my first problem was here in my xpath!

I was erroneously trying to use the /* instead of placing the [] immediately after object.

```
root/objects/object/*[position()=1]
```
vs

```
objects/object[position()!=1 and position()!=last()]
```
