### ISSUE TITLE
Segment is missing in output produced by "javascript_with_context"

### ISSUE THREAD

**Issue by lg-RahulYadav** [jf-tech/omniparser#204]
Steps to reproduce the error:

- Have a schema at least 3 - 4 level nested.
- make sure you don't have elements details mentioned in schema, basically selecting no elements from particular segment in schema.

For me, I'm able to reproduce using below schema

`{
    "name": "TDT",
    "min": 1,
    "max": 99,
    "elements": [],
    "child_segments": [
        {
            "name": "LOC",
            "min": 0,
            "max": 99,
            "elements": [
                {
                    "name": "reference",
                    "index": 1
                }
            ],
            "child_segments":[
                {
                    "name": "DTM",
                    "min": 0,
                    "max": 9,
                    "elements": [
                        {
                            "name": "date",
                            "index": 1
                        }
                    ]
                }
            ]
        }
    ]
}`

and transform_declaration is:
`"transform_declarations": {
        "FINAL_OUTPUT": {
            "object": {
                "data": {
                    "custom_func": {
                        "name": "javascript_with_context",
                        "args": [
                            {
                                "const": "JSON.parse(_node)"
                            }
                        ]
                    }
                }
            }
        }
    }`
    
and the output is:
`
"TDT": [
    [
        {
            "DTM": {
                "date": "2"
            },
            "reference": "10"
        },
        {
            "reference": "7"
        }
    ],
    [
        {
            "reference": "9"
        },
        {
            "DTM": {
                "date": "10"
            },
            "reference": "12"
        }
    ]
]
`
segment "LOC" is missing.

The issue is not happening if I add element details for TDT segment. 

Let me know if any other details are required?

**Comment by jf-tech** [comment]
@lg-RahulYadav the situation you encountered is very subtle and took me a while to refresh my memory about the issue/delicacy about it.

Let's look at some simplified examples here:

### Input 1:
```
TDT:1
LOC:ref1

```
(Note the trailing white line)

### Schema 1:
```
{
    "parser_settings": {
        "version": "omni.2.1",
        "file_format_type": "edi"
    },
    "file_declaration": {
        "segment_delimiter": "\n",
        "element_delimiter": ":",
        "segment_declarations": [
            {
                "name": "TDT",
                "is_target": true,
                "child_segments": [
                    {
                        "name": "LOC",
                        "max": -1,
                        "elements": [ { "name": "reference", "index": 1 } ]
                    }
                ]
            }
        ]
    },
    "transform_declarations": {
        "FINAL_OUTPUT": { "object": {
            "data": { "custom_func": {
                "name": "javascript_with_context",
                "args": [ { "const": "JSON.parse(_node)" } ]
            }}
        }}
    }
}
```

### Output 1:
(by running `./cli.sh transform -i input -s schema`)
```
[
	{
		"data": {
			"LOC": {
				"reference": "ref1"
			}
		}
	}
]
```

The `"LOC"` is there! Now change the input to:

### Input 2:
```
TDT:1
LOC:ref1
LOC:ref2

```
(Note the trailing white line)

### Schema 2:
Use the same Schema 1.

### Output 2:
```
[
	{
		"data": [
			{
				"reference": "ref1"
			},
			{
				"reference": "ref2"
			}
		]
	}
]
```

Now the `"LOC"` field is gone, instead `"data"` is turned into a JSON array.

### Input 3:
```
TDT:1
LOC:ref1
LOC:ref2

```
Same as Input 2.
(Note the trailing white line)

### Schema 3:
```
{
    "parser_settings": {
        "version": "omni.2.1",
        "file_format_type": "edi"
    },
    "file_declaration": {
        "segment_delimiter": "\n",
        "element_delimiter": ":",
        "segment_declarations": [
            {
                "name": "TDT",
                "is_target": true,
                "elements": [ { "name": "tdt_id", "index": 1 } ]
                "child_segments": [
                    {
                        "name": "LOC",
                        "max": -1,
                        "elements": [ { "name": "reference", "index": 1 } ]
                    }
                ]
            }
        ]
    },
    "transform_declarations": {
        "FINAL_OUTPUT": { "object": {
            "data": { "custom_func": {
                "name": "javascript_with_context",
                "args": [ { "const": "JSON.parse(_node)" } ]
            }}
        }}
    }
}
```
Basically the difference is adding `element` for `TDT`.

### Output 3:
```
[
	{
		"data": {
			"LOC": [
				{
					"reference": "ref1"
				},
				{
					"reference": "ref2"
				}
			],
			"tdt_id": "1"
		}
	}
]
```
`"LOC"` is back but it's an array. and `"data"` is now back to a JSON object.

### Explanation

When we read data in, they're are stored in [IDR](https://github.com/jf-tech/omniparser/blob/master/doc/idr.md) format which is an in-memory data structure that is very flexible. But when you use `javascript_with_context`, it needs to jsonify the current IDR node into a JSON string as an argument passing to the javascript engine.

The jsonify uses this method [`J2NodeToInterface`](https://github.com/jf-tech/omniparser/blob/master/idr/marshal2.go#L206). Now if you trace down into the method, you'll see all the glory/gory details in dealing with messy XML/EDI situation:

In particular, in method [`nodeToInterface`](https://github.com/jf-tech/omniparser/blob/master/idr/marshal2.go#L138) it needs to determine whether the current IDR node is a regular text node, an object node, or an array node. And that determination, specially for the case of [`isChildArray`](https://github.com/jf-tech/omniparser/blob/master/idr/marshal2.go#L67) is done heuristically. Hopefully the detailed comment in the function reveals some insight here:

```
	// CSV or fixed-length formats won't produce array.
	//
	// JSONStreamReader, when encountered actual array in JSON input, produces
	// a collection of child element nodes with their Data fields all equal to
	// empty string.
	//
	// XML/EDI are a bit more complicated:
	// There is no concept of array in XML, neither in EDI. XML, however, can simulate
	// array by having a number of child elements with the same element name. EDI has
	// segment loop. So the primary idea is to check child element nodes' names and use
	// their similarity to determine whether the children represent an array or not.
	// Throwing a wrench here is that fact in XML, there are dummy text nodes sprinkled
	// around, in between XML elements, so we need to ignore them. There could also be
	// attribute nodes in XML, need to ignore them too.
	//
	// One ambiguous case in XML (and similarly in EDI):
	//   <abc>
	//      <child>something</child>
	//   </abc>
	// We can consider node 'abc' contains a field 'child', or we can consider node 'abc'
	// contains an array of one element which is 'child'. There is really no other signs/flags
	// help us to disambiguate the situation. So use common sense here, treat this situation
	// like a single child field, instead of a child array with one element. EDI is similar.
	// EDI doesn't have some indicator (i.e. a segment can have multiple instances), but it's
	// too hard to pass the indicator here. So hope this promise/limitation is acceptable.
```

In essence, in our example 1, since there is only one `LOC` under `TDT`, `TDT` is treated as an object, and `LOC` is treated as a sub-field.

In our example 2, since there are two `LOC`s under `TDT` and nothing else under `TDT`, thus `TDT` is treated as an array, and `LOC`s are array elements, thus array elements are nameless.

In our example 3, there are two `LOC`s under `TDT` but `TDT` itself has some data, namely `tdt_id`, thus the jsonify code treat `TDT` as object, and `tdt_id` as a field, and `LOC` as a field. However, since we have two `LOC` nodes here, to avoid overwriting each other, we turn the `LOC` field into a JSON array. See the comments in the method [`nodeToInterface`](https://github.com/jf-tech/omniparser/blob/master/idr/marshal2.go#L161-L202), you can see the rationales:
```
				// Both in XML and EDI, we can potentially have something like the following:
				//   <abc>
				//     <efg>1</efg>
				//     <efg>2</efg>
				//     <xyz>3</xyz>
				//   </abc>
				// We don't want to overwrite first <efg> with second <efg>. So instead we
				// will return something like this:
				//  map[string]interface{} {
				//    "efg": [ "1", "2" ],
				//    "xyz": "3"
				//  }
```


After all these explanation, the subtlety is only manifested when you use `javascript_with_context` and use `JSON.parse(_node)` code. There isn't much we can do I have to say. If you really really need the `LOC` field name, just toss in some dummy `TDT` elements.

Any other questions let me know.

**Comment by jf-tech** [comment]
@lg-RahulYadav I'll close the ticket in a couple days if no more questions/updates. thanks.

**Comment by lg-RahulYadav** [comment]
Thanks for the explanation, much appreciated.

**Comment by lg-RahulYadav** [comment]
Closing the issue as it has been answered.
