### ISSUE TITLE
fixedLength2 with footer failing. 

### ISSUE THREAD

**Issue by scotthedge** [jf-tech/omniparser#205]
Hi I'm trying to understand why parsing of this fixed length file is failing. 
Error: input 'CNHI_input.txt' line 9: envelope/envelope_group 'FOOTER' needs min occur 1, but only got 0
I get that it's not finding the footer envelope, I'm just not sure why. I appreciate any help

the schema and input seem to be very similar to the example here: https://github.com/jf-tech/omniparser/blob/master/extensions/omniv21/samples/fixedlength2/3_header_footer.schema.json

[CNHI_input.txt](https://github.com/jf-tech/omniparser/files/11826067/CNHI_input.txt)

[CNHI_schema.txt](https://github.com/jf-tech/omniparser/files/11826097/CNHI_schema.txt)

**Comment by jf-tech** [comment]
I see the problem. I probably need to update [the fixed-length documentation](https://github.com/jf-tech/omniparser/blob/master/doc/fixedlength2_in_depth.md) to explain the situation more:

Your schema declares 3 envelopes, the issue there is "mismatch" of the envelope identifier among the 3 envelopes. 

The first and last envelope are declared using pattern matching (1st one uses `"header": "^A"` and last one uses `"header": "^T"`), while the second envelope is declared using row counting (`"rows": 1`, but generally this directive is omitted and 1 is defaulted, for schema brevity).

The problem is once omniparser enters the 2nd envelope parsing, it will never be able to get out, until EOF, right? Think about it, the 2nd envelope says, each instance of this envelope is a single line. Well, any line is single line. Thus, omniparser will suck in the last footer line in as an instance of the 2nd envelope. Once it hits the EOF, it checks the remainder of the envelopes, and noticing the `FOOTER` envelope requires `min=1` but didn't parse in any instance of it, thus failing.

How to fix your problem? Some ideas:

- If you don't need any data from the file's footer, just don't declare the `FOOTER` envelope. :)
- if you really need some data from `FOOTER`, then you probably have to change the `RECORDS` envelope to be pattern matching as well, seems like you records have prefixes like `E/M`, etc. you can probably come up with a regex to match that.

Let me know if any other questions you have.

**Comment by scotthedge** [comment]
Thanks for the reply. It makes sense that it won't find the footer without the records envelope having some kind of boundary on it. It processes without the footer envelope, but then of course it treats the footer row as a record. We might just manually ignore the last row of data or something similar if we can't pattern match the records.
