### ISSUE TITLE
[EDI] Schema Output Configuration | Unable to access ancestor segments via xpath

### ISSUE THREAD

**Issue by manuel-neuhauser-hs** [jf-tech/omniparser#217]
For an EDI file with a nested segment set to `is_target: true`, I'm unable to access higher level segments beyond direct ancestors.

For example, using _xpath_ to navigate up the hierarchy to the `functional_groups` segment and then down to the `GE` segment returns no values yields no result.

```
xpath: ../../GE/GE01
       ^  ^
       GS |
          functional_groups
```

### Simplified Segment Declaration
```
ISA ✅
  functional_groups (type: segment_group)
    GS ✅
      transactions (type: segment_group, is_target: true)
        ST ✅
        [...]
        SE ✅
    GE ❌
IEA ❌
```

### Example FINAL_OUTPUT Configuration

```json
    "FINAL_OUTPUT": {
      "object": {
        "st_header": {
          "xpath": "ST/ST01"
        },
        "se_footer": {
          "xpath": "SE/SE01"
        },
        "gs_header": {
          "xpath": "../../GS/GS01"
        },
        "ge_footer": {
          "xpath": "../../GE/GE01"
        },
        "isa_header": {
          "xpath": "../../../../ISA/ISA01"
        },
        "iea_footer": {
          "xpath": "../../../../IEA/IEA01"
        }
      }
```

### Example Output
Note that `ge_footer` and `iea_footer` are not present.

```json
[
  {
    "gs_header": "BE",
    "isa_header": "00",
    "se_footer": "159",
    "st_header": "834"
  },
  {
    "gs_header": "BE",
    "isa_header": "00",
    "se_footer": "159",
    "st_header": "834"
  },
  {
    "gs_header": "BE",
    "isa_header": "00",
    "se_footer": "159",
    "st_header": "834"
  },
  {
    "gs_header": "BE",
    "isa_header": "00",
    "se_footer": "159",
    "st_header": "834"
  }
]
```

### Command

```bash
op transform --schema 834-schema.json.txt --input edi834.txt
```

### Files
[edi834.txt](https://github.com/jf-tech/omniparser/files/12490101/edi834.txt)
[834-schema.json.txt](https://github.com/jf-tech/omniparser/files/12490133/834-schema.json.txt)

Is there an issue with my schema file, or is accessing these values not supported? Thanks in advance.

**Comment by jf-tech** [comment]
@manuel-neuhauser-hs good question.

Yes, you're not able to because omniparser is designed as a streaming parser. As it reads in and builds the hierarchical tree (in [IDR](https://github.com/jf-tech/omniparser/blob/master/doc/idr.md#edi)), when it encounters and finishes ingesting and transforming a segment marked with `is_target: true`, it will return to the caller's `transform.Read()` call. In your case, the later segments `GE` `IEA` haven't even been read it yet. There is no magic about it. And currently we don't have any way of out of sequence read, or something like 2-pass reading.

One potential solution, depending on your input EDI file size, is to:
* put `IEA` under `ISA`, similarly put `GE` as a child segment of `GS` and `SE` as child of `ST`. That in some way makes sense, because `IEA`, `GE`, `SE` are indeed the respective closing segs for `ISA`, `GS`, `ST`.
* put `is_target: true` onto `ISA`. This way, you basically read the entire EDI file in one block, all info will be available.
* Your transform needs to deal with the repeated transaction group (segment_group) as `array` under `transform_declarations`. Somewhat resembles transforms done here: https://github.com/jf-tech/omniparser/blob/master/extensions/omniv21/samples/edi/2_ups_edi_210.schema.json#L200

Let me know if you have additional questions.

**Comment by manuel-neuhauser-hs** [comment]
Thanks for the insight. I'll try the proposed solution.
